// This ends up pointing to a CJS version of the ES module generated by wasm-pack
// which is done post-compile via rollup

const {
    wasm, requireWasmInitialized
} = require('./init_wasm');

module.exports.boundCheckSnarkSetup = (returnUncompressed) => {
    requireWasmInitialized();
    return wasm.boundCheckSnarkSetup(returnUncompressed);
};
