// This ends up pointing to a CJS version of the ES module generated by wasm-pack
// which is done post-compile via rollup

const {
    wasm, requireWasmInitialized
} = require('./init_wasm');

module.exports.boundCheckSnarkSetup = () => {
    requireWasmInitialized();
    return wasm.boundCheckSnarkSetup();
};

module.exports.boundCheckDecompressSnarkPk = (snarkPk) => {
    requireWasmInitialized();
    return wasm.boundCheckDecompressSnarkPk(snarkPk);
};

module.exports.boundCheckGetSnarkVkFromPk = (snarkPk) => {
    requireWasmInitialized();
    return wasm.boundCheckGetSnarkVkFromPk(snarkPk);
};
