// This ends up pointing to a CJS version of the ES module generated by wasm-pack
// which is done post-compile via rollup

const {
    wasm, requireWasmInitialized
} = require('./init_wasm');

module.exports.legosnarkDecompressPk = (snarkPk) => {
    requireWasmInitialized();
    return wasm.legosnarkDecompressPk(snarkPk);
};

module.exports.legosnarkVkFromPk = (snarkPk, returnUncompressed) => {
    requireWasmInitialized();
    return wasm.legosnarkVkFromPk(snarkPk, returnUncompressed);
};

module.exports.legosnarkDecompressVk = (snarkVk) => {
    requireWasmInitialized();
    return wasm.legosnarkDecompressVk(snarkVk);
};
