// This ends up pointing to a CJS version of the ES module generated by wasm-pack
// which is done post-compile via rollup
/*const {
    generatePoKBBSSignatureStatement, generateAccumulatorMembershipStatement,
    generateAccumulatorNonMembershipStatement, generatePedersenCommitmentStatement, generateWitnessEqualityMetaStatement,
    generatePoKBBSSignatureWitness, generateAccumulatorMembershipWitness, generateAccumulatorNonMembershipWitness,
    generatePedersenCommitmentWitness, generateProofSpec, generateCompositeProof, verifyCompositeProof,
    getProofSpecAsJson, getProofSpecFromJson
} = require("./index");*/

const {
    wasm, requireWasmInitialized
} = require('./init_wasm');

module.exports.generatePoKBBSSignatureStatement = (params, publicKey, revealedMessages, encodeMessages) => {
    requireWasmInitialized();
    return wasm.generatePoKBBSSignatureStatement(params, publicKey, revealedMessages, encodeMessages);
};

module.exports.generateAccumulatorMembershipStatement = (params, publicKey, provingKey, accumulated) => {
    requireWasmInitialized();
    return wasm.generateAccumulatorMembershipStatement(params, publicKey, provingKey, accumulated);
};

module.exports.generateAccumulatorNonMembershipStatement = (params, publicKey, provingKey, accumulated) => {
    requireWasmInitialized();
    return wasm.generateAccumulatorNonMembershipStatement(params, publicKey, provingKey, accumulated);
};

module.exports.generatePedersenCommitmentG1Statement = (bases, commitment) => {
    requireWasmInitialized();
    return wasm.generatePedersenCommitmentG1Statement(bases, commitment);
};

module.exports.generatePedersenCommitmentG2Statement = (bases, commitment) => {
    requireWasmInitialized();
    return wasm.generatePedersenCommitmentG2Statement(bases, commitment);
};

module.exports.generateWitnessEqualityMetaStatement = (equalities) => {
    requireWasmInitialized();
    return wasm.generateWitnessEqualityMetaStatement(equalities);
};

module.exports.generatePoKBBSSignatureWitness = (signature, unrevealedMessages, encodeMessages) => {
    requireWasmInitialized();
    return wasm.generatePoKBBSSignatureWitness(signature, unrevealedMessages, encodeMessages);
};

module.exports.generateAccumulatorMembershipWitness = (element, witness) => {
    requireWasmInitialized();
    return wasm.generateAccumulatorMembershipWitness(element, witness);
};

module.exports.generateAccumulatorNonMembershipWitness = (element, witness) => {
    requireWasmInitialized();
    return wasm.generateAccumulatorNonMembershipWitness(element, witness);
};

module.exports.generatePedersenCommitmentWitness = (elements) => {
    requireWasmInitialized();
    return wasm.generatePedersenCommitmentWitness(elements);
};

module.exports.generateProofSpec = (statements, metaStatements, context) => {
    requireWasmInitialized();
    return wasm.generateProofSpec(statements, metaStatements, context);
};

module.exports.getProofSpecAsJson = (proofSpec) => {
    requireWasmInitialized();
    return wasm.getProofSpecAsJson(proofSpec);
};

module.exports.getProofSpecFromJson = (json) => {
    requireWasmInitialized();
    return wasm.getProofSpecFromJson(json);
};

module.exports.generateCompositeProof = (proofSpec, witnesses, nonce) => {
    requireWasmInitialized();
    return wasm.generateCompositeProof(proofSpec, witnesses, nonce);
};

module.exports.verifyCompositeProof = (proof, proofSpec, nonce) => {
    requireWasmInitialized();
    return wasm.verifyCompositeProof(proof, proofSpec, nonce);
};
